// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwmvmeqjhwqlvnxfifca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bXZtZXFqaHdxbHZueGZpZmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDc1MTgsImV4cCI6MjA2MjEyMzUxOH0.hMj-KfYuyPs2IGSaQ00wuNprLDUbVHI2M6HoetDFzFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);